
title = "Gabe Dalay"
baseurl = "/"
languageCode = "en-us"
theme = "m10c"
paginate = 5
publishdir = "./"

[params]
  author = "Gabe Dalay"
  description = "Thoughts of a gabe. Topics including software engineering, health/fitness/nutrition, music, cooking and coffee."
  [[params.social]]
    name = "github"
    url = "https://github.com/jebrial"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/gabedalay"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/gabrieldalay/"
  [[params.social]]
    name = "instagram"
    url = "https://www.instagram.com/jebrial/"
  [[params.social]]
    name = "soundcloud"
    url = "https://soundcloud.com/xjebrialx"
  [params.style]
    darkestColor = "#f1f1f1"
    darkColor = "#fff"
    lightColor = "#606060"
    lightestColor = "#707070"
    primaryColor = "#334865"

# theme = "hello-friend"
# [params]
#   # dir name of your blog content (default is `content/posts`)
#   contentTypeName = "posts"

#   # "light" or "dark"
#   defaultTheme = "dark"

#   # if you set this to 0, only submenu trigger will be visible
#   showMenuItems = 2

#   # Show reading time in minutes for posts
#   showReadingTime = false

# [languages]
#   [languages.en]
#     title = "gabe dalay"
#     subtitle = "thoughts of a gabe."
#     keywords = "software development, coffee, baking, cooking, exercise, nutrition, rust, javascript, music, guitar, audio software, iot"
#     copyright = "2020"
#     menuMore = "Show more"
#     writtenBy = "Written by"
#     readMore = "Read more"
#     readOtherPosts = "Read other posts"
#     newerPosts = "Newer posts"
#     olderPosts = "Older posts"
#     minuteReadingTime = "min read"
#     dateFormatSingle = "2006-01-02"
#     dateFormatList = "2006-01-02"
#     # leave empty to disable, enter display text to enable
#     # lastModDisplay = ""

#     [languages.en.params.logo]
#       logoText = "gabe.dalay $>"
#       logoHomeLink = "/"
#     # or
#     #
#     # path = "/img/your-example-logo.svg"
#     # alt = "Your example logo alt text"

#     [languages.en.menu]
#       [[languages.en.menu.main]]
#         identifier = "about"
#         name = "About"
#         url = "/about"
#       [[languages.en.menu.main]]
#         identifier = "showcase"
#         name = "Showcase"
#         url = "/showcase"